### ISSUE TITLE
question marks in folder/image names don't work right

### ISSUE THREAD

**Issue by jmberg** [tingvold/photofloat#3]
I have fixes, but not so trivial to cherry-pick and I don't even have a github fork ...

https://p.sipsolutions.net/25aa2dec346681bc.txt
https://p.sipsolutions.net/45457ac4009b4baf.txt

**Comment by joachimtingvold** [comment]
I guess I'm late to the party; did not see these issues before now. Thanks for the fixes, but I'll just go ahead and archive this repo.

I no longer maintain any photofloat versions or installations anymore, as I've moved on to using [PhotoPrism ](https://github.com/photoprism/photoprism) as my photo gallery.
