### ISSUE TITLE
touch friendly UI

### ISSUE THREAD

**Issue by jmberg** [tingvold/photofloat#4]
It'd be nice to make the UI touch friendly :-)

I (crudely!) combined photofloat with blueimp/Gallery here:
https://git.sipsolutions.net/photofloat.git/log/?h=blueimp

That lost a few features, but mostly works OK (there's a bug when you click a picture it doesn't always open properly but ...)

**Comment by joachimtingvold** [comment]
I guess I'm late to the party; did not see these issues before now. Thanks for the fixes, but I'll just go ahead and archive this repo.

I no longer maintain any photofloat versions or installations anymore, as I've moved on to using [PhotoPrism ](https://github.com/photoprism/photoprism) as my photo gallery.
